### ISSUE TITLE
Error: tabLayout.setOnTabSelectedListener(this); on tns run.

### ISSUE THREAD

**Issue by phlegx** [Akylas/nativescript-material-components#76]
### Which platform(s) does your issue occur on?
- Android
- Android min. SDK 21
- tns run

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.1.2
- Runtime(s): iOS 6.1.1, Android 6.1.2 

### Please, tell us how to recreate the issue in as much detail as possible. 

After upgrade from `nativescript-material-ripple` v2.4.2 to v2.5.4 I get this error with `tns run`:

```
/app/platforms/android/app/src/debug/java/com/tns/ErrorReport.java:294: error: incompatible types: ErrorReport cannot be converted to BaseOnTabSelectedList
ener
        tabLayout.setOnTabSelectedListener(this);
                                           ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### Is there any code involved? 
 - No changes made to my code. Only upgraded to new `nativescript-material-ripple` v2.5.4.

**Comment by farfromrefug** [comment]
@phlegx Can you try to remove the platforms folder?

**Comment by farfromrefug** [comment]
ok that s bad you can try for now to force version 2.5.2 it should work

**Comment by phlegx** [comment]
@farfromrefug v2.5.2 of `nativescript-material-ripple` don't work. Same error!

**Comment by farfromrefug** [comment]
@phlegx sorry yes that s normal. it is because ```nativescript-material-ripple``` depends on ```nativescript-material-core``` with ```^2.5.2``` which means it would still get 2.5.4 of ```nativescript-material-core```. You can force ```nativescript-material-core``` to 2.5.2 in your package.json.
Sorry!

**Comment by phlegx** [comment]
I understand, thx. I will try it.

**Comment by fvdung** [comment]
> One way to fix this and use the latest version of this component is to use rc version of the android runtime

Use version 2.5.4 with tns-core-modules@rc I get a navigation error with the bottom navigation element.
Specifically, I cannot navigateBack to the page contain BottomNavigation element. 
I catch logs

```
The specified child already has a parent. You must call removeView() on the child's parent first.
System.err:
System.err: StackTrace:
System.err: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
```

**Comment by fvdung** [comment]
> It is now an issue with the android runtime [NativeScript/android-runtime#1494](https://github.com/NativeScript/android-runtime/issues/1494)
> One way to fix this and use the latest version of this component is to use rc version of the android runtime

Use version 2.5.4 with tns-core-modules@rc I get a navigation error with the bottom navigation element.
Specifically I cannot navigate back to the page containing the BottomNavigation element. 
I got an error 
```
The specified child already has a parent. You must call removeView() on the child's parent first.
System.err:
System.err: StackTrace:
System.err: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
.....
```

**Comment by farfromrefug** [comment]
@fvdung not tns core modules! Android runtime

**Comment by johny8228** [comment]
@phlegx I had the same issue when migrating my project to NS 6+.I fixed this by using RC version for Nativescript CLI . You can do this by changing in package.json : 
"tns-android": {
      "version": "rc"
    }
You also need to clean up platforms directory before.

**Comment by farfromrefug** [comment]
@johny8228 it s not the cli you updated, its the android runtime

**Comment by johny8228** [comment]
@farfromrefug sorry my bad.I edited the comment. Thank you.
